transactions_per_second = 1
merchant_slug = "wasabi-club"
payment_provider = "visa"
deployed_slug = "wasabi-club"
routing_key = "transactions.*.perf-wasabi-club"
batch_size = 100
amount_min = 100
amount_max = 30000
