transactions_per_second = 1
merchant_slug = "wasabi-club"
payment_provider = "visa"
deployed_slug = "visa-auth"
routing_key = "transactions.*.perf-wasabi-club"
batch_size = 5
amount_min = 100
amount_max = 30000
maximum_number_transactions = 5
percentage = [['visa', 100], ['mastercard', 0], ['amex', 0]]
