transactions_per_second = 1
provider_slug = "iceland-bonus-card"
routing_key = "transactions.*.iceland-bonus-card"
amount_min = 100
amount_max = 20000
percentage = [['visa', 100], ['mastercard', 0], ['amex', 0]]
batch_size = 10000

[sender.Blob]
account = "uksouthdev374l"
access_key = "get_key_from_azure"
container = "harmonia-imports-test/iceland"
