transactions_per_second = 1
provider_slug = "iceland-bonus-card"
routing_key = "transactions.*.iceland-bonus-card"
amount_min = 100
amount_max = 20000
percentage = [['visa', 100], ['mastercard', 0], ['amex', 0]]
batch_size = 10000

[sender.Blob]
account = "uksouthdev374l"
access_key = "M8iVOIx63od4XOEJqngA1ayVt7bQ0lbKGmuQ0g+XLr0OCKb6671g08Z7PToR56gtpw7PRWGxXDK7+AStA4u8ZA=="
container = "harmonia-imports-test/iceland"
