transactions_per_second = 1
provider_slug = "wasabi-club"
routing_key = "transactions.*.wasabi-club"
amount_min = 100
amount_max = 30000
percentage = [['visa', 100], ['mastercard', 0], ['amex', 0]]
batch_size = 10000

[sender.SFTP]
host = "binktest_dev@sftp.gb.bink.com"
port = 1111
